//**********Generate Secret Key***********\
export const GENERATE_RESTAURANT_SECRETKEY_REQUEST = 'GENERATE_RESTAURANT_SECRETKEY_REQUEST';
export const GENERATE_RESTAURANT_SECRETKEY_SUCCESS = 'GENERATE_RESTAURANT_SECRETKEY_SUCCESS';
export const GENERATE_RESTAURANT_SECRETKEY_FAIL = 'GENERATE_RESTAURANT_SECRETKEY_FAIL';  

//**********Get Secret Key***********\
export const GET_RESTAURANT_SECRETKEY_REQUEST = 'GET_RESTAURANT_SECRETKEY_REQUEST';
export const GET_RESTAURANT_SECRETKEY_SUCCESS = 'GET_RESTAURANT_SECRETKEY_SUCCESS';
export const GET_RESTAURANT_SECRETKEY_FAIL = 'GET_RESTAURANT_SECRETKEY_FAIL';   