// ***********************CREATE RESTAURANT********************
export const CREATE_RESTAURANT_REQUEST = 'CREATE_RESTAURANT_REQUEST';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const CREATE_RESTAURANT_FAIL = 'CREATE_RESTAURANT_FAIL';

// ***********************GET RESTAURANT DETAIL********************
export const GET_RESTAURANT_DETAIL_REQUEST = 'GET_RESTAURANT_DETAIL_REQUEST';
export const GET_RESTAURANT_DETAIL__SUCCESS = 'GET_RESTAURANT_DETAIL__SUCCESS';
export const GET_RESTAURANT_DETAIL_FAIL = 'GET_RESTAURANT_DETAIL_FAIL'; 